version: '3.8'

services:
  eureka-server:
    build:
      context: ./EurekaServer
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  api-gateway:
    build:
      context: ./ApiGateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      eureka-server:
        condition: service_healthy
    command: ["java", "-jar", "/app/api-gateway.jar"]
    networks:
      - eureka-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  cycle-service:
    build:
      context: ./CycleService
      dockerfile: Dockerfile
    container_name: cycle-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://cycle-mongo:27017/cycle_database
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8081:8081"
    depends_on:
      cycle-mongo:
        condition: service_started
      eureka-server:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - eureka-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://user-mongo:27017/user_database
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8083:8083"
    depends_on:
      user-mongo:
        condition: service_started
      eureka-server:
        condition: service_healthy
    networks:
      - eureka-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  daily-usage-service:
    build:
      context: ./DailyUsageService
      dockerfile: Dockerfile
    container_name: daily-usage-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://daily-usage-mongo:27017/daily_usage_database
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8082:8082"
    depends_on:
      daily-usage-mongo:
        condition: service_started
      eureka-server:
        condition: service_healthy
      cycle-service:
        condition: service_healthy
    networks:
      - eureka-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  cycle-mongo:
    image: mongo:latest
    container_name: cycle-mongo
    ports:
      - "27017:27017"
    volumes:
      - cycle-mongo-data:/data/db
    networks:
      - eureka-network

  user-mongo:
    image: mongo:latest
    container_name: user-mongo
    ports:
      - "27018:27017"
    volumes:
      - user-mongo-data:/data/db
    networks:
      - eureka-network

  daily-usage-mongo:
    image: mongo:latest
    container_name: daily-usage-mongo
    ports:
      - "27019:27017"
    volumes:
      - daily-usage-mongo-data:/data/db
    networks:
      - eureka-network

volumes:
  cycle-mongo-data:
  user-mongo-data:
  daily-usage-mongo-data:

networks:
  eureka-network:
    driver: bridge
