spring:
  application:
    name: DailyUsageService

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    health-check-url-path: /actuator/health

server:
  port: 8082
  forward-headers-strategy: framework
#
#springdoc:
#  swagger-ui:
#    path:
